---
- name: Capture apache2 os version
  hosts: all
  tasks:
    - name: Install apache2 using apt
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Install httpd suing yum
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
    - name: edit the html file
      copy:
        content: "WELCOME"
        dest: /var/www/html/index.html
    - name: Restart apache2
      service:
        name: apache2
        state: restarted
      when: ansible_distribution == "Ubuntu"
    - name: Restart httpd
      service:
        name: httpd
        state: restarted
      when: ansible_distribution == "RedHat"
...
