---
- name: Create a multiple users using loops
  hosts: all
  tasks:
    - name: Create users
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        comment: "{{item.c}}"
        shell: /bin/bash
      with_items:
        - {a: Puppy,b: hello,c: wellcome}
        - {a: Krish,b: hie,c: handsome}
        - {a: Navyan,b: bro,c: cutie}
...

        


