---
- name: create a user and create a file/dir in user home
  hosts: 172.31.3.191
  tasks:
    - name: create a user 
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
        comment: "{{d}}"
    - name: create a file in user home
      file: 
        name: "{{e}}"
        state: "{{f}}"



...



