---
- name: create a user
  hosts: all
  vars:
   - a: harish
   - b: manu
   - c: /home/harish
   - d: wellcome
  tasks:
    - name: create a user
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
        comment: "{{d}}"
...

