---
- name: create a user and create a file in user home
  hosts: all
  tasks:
    - name: create a user
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
    - name: create file in user home 
      file:
        name: "{{d}}"
        state: "{{e}}"


...

