---
- name: Install/uninstall s/w application
  hosts: all
  tasks: 
    - name: Install/uninstall multiple s/w applications
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tree, b: present, c: no}
        - {a: git,  b: present, c: yes}
        - {a: maven, b: present, c: no}   
...
