---
- name: create user using host scope varaiable
  hosts: 172.31.19.64
  tasks: 
    - name: create a user
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
        shell: "{{d}}"
        comment: "{{e}}"

...
