---
- name: check if a floder called f1 is present if not create a file called f1
  hosts: all
  tasks:
    - name: check for f1 directory
      stat:
        path: /home/ubuntu/f1
      register: a
    - name: Display output of above module 
      debug:
        var: a
    - name: create a file f1 if dir f1 is not present 
      file:
        name: /home/ubuntu/f1
        state: touch
      when: a.stat.exists == false
...
