---
- name: tomcat9 s/w applications
  hosts: all
  tasks:
    - name: Calling child playbooks
      include_tasks: "{{item}}"
      with_items:
        - tomcat_install.yml
        - tomcat_copy.yml
        - tomcat_replace.yml
        - tomcat_restart.yml
        - tomcat_uri.yml
...






